/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class PassengerInfo {
    id: string;
    name: string;
    certificateType: string;
    certificateNo: string;
    phone: string;

    constructor() {
    }

    getFieldTypeMap():  Map<string, string> {
        let fieldTypeMap = new Map<string, string>();
        fieldTypeMap.set('id', 'String');
        fieldTypeMap.set('name', 'String');
        fieldTypeMap.set('certificateType', 'String');
        fieldTypeMap.set('certificateNo', 'String');
        fieldTypeMap.set('phone', 'String');
        return fieldTypeMap;
    }

    getClassName(): string {
        return 'PassengerInfo';
    }

    getPrimaryKeyList(): string[] {
        let primaryKeyList: string[] = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList(): string[] {
        let indexList: string[] = [];
        return indexList;
    }

    getEncryptedFieldList(): string[] {
        let encryptedFieldList: string[] = [];
        return encryptedFieldList;
    }

    setId(id: string): void {
        this.id = id;
    }

    getId(): string  {
        return this.id;
    }

    setName(name: string): void {
        this.name = name;
    }

    getName(): string  {
        return this.name;
    }

    setCertificateType(certificateType: string): void {
        this.certificateType = certificateType;
    }

    getCertificateType(): string  {
        return this.certificateType;
    }

    setCertificateNo(certificateNo: string): void {
        this.certificateNo = certificateNo;
    }

    getCertificateNo(): string  {
        return this.certificateNo;
    }

    setPhone(phone: string): void {
        this.phone = phone;
    }

    getPhone(): string  {
        return this.phone;
    }

    static parseFrom(inputObject: any): PassengerInfo {
        let result = new PassengerInfo();
        if (!inputObject) {
            return result;
        }
        if (inputObject.id) {
            result.id = inputObject.id;
        }
        if (inputObject.name) {
            result.name = inputObject.name;
        }
        if (inputObject.certificateType) {
            result.certificateType = inputObject.certificateType;
        }
        if (inputObject.certificateNo) {
            result.certificateNo = inputObject.certificateNo;
        }
        if (inputObject.phone) {
            result.phone = inputObject.phone;
        }
        return result;
    }
}

export { PassengerInfo };