/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class UserInfo {
    idToken: string;
    authCode: string;
    userName: string;
    avatar: string;
    phoneNumber: string;

    constructor() {
    }

    getFieldTypeMap():  Map<string, string> {
        let fieldTypeMap = new Map<string, string>();
        fieldTypeMap.set('idToken', 'String');
        fieldTypeMap.set('authCode', 'String');
        fieldTypeMap.set('userName', 'String');
        fieldTypeMap.set('avatar', 'String');
        fieldTypeMap.set('phoneNumber', 'String');
        return fieldTypeMap;
    }

    getClassName(): string {
        return 'UserInfo';
    }

    getPrimaryKeyList(): string[] {
        let primaryKeyList: string[] = [];
        primaryKeyList.push('idToken');
        return primaryKeyList;
    }

    getIndexList(): string[] {
        let indexList: string[] = [];
        return indexList;
    }

    getEncryptedFieldList(): string[] {
        let encryptedFieldList: string[] = [];
        return encryptedFieldList;
    }

    setIdToken(idToken: string): void {
        this.idToken = idToken;
    }

    getIdToken(): string  {
        return this.idToken;
    }

    setAuthCode(authCode: string): void {
        this.authCode = authCode;
    }

    getAuthCode(): string  {
        return this.authCode;
    }

    setUserName(userName: string): void {
        this.userName = userName;
    }

    getUserName(): string  {
        return this.userName;
    }

    setAvatar(avatar: string): void {
        this.avatar = avatar;
    }

    getAvatar(): string  {
        return this.avatar;
    }

    setPhoneNumber(phoneNumber: string): void {
        this.phoneNumber = phoneNumber;
    }

    getPhoneNumber(): string  {
        return this.phoneNumber;
    }

    static parseFrom(inputObject: any): UserInfo {
        let result = new UserInfo();
        if (!inputObject) {
            return result;
        }
        if (inputObject.idToken) {
            result.idToken = inputObject.idToken;
        }
        if (inputObject.authCode) {
            result.authCode = inputObject.authCode;
        }
        if (inputObject.userName) {
            result.userName = inputObject.userName;
        }
        if (inputObject.avatar) {
            result.avatar = inputObject.avatar;
        }
        if (inputObject.phoneNumber) {
            result.phoneNumber = inputObject.phoneNumber;
        }
        return result;
    }
}

export { UserInfo };