

export enum MainServiceMap {
  COURSES_COLUMN,
  ONLINE_COURSES,
  OFFLINE_STORE,
  ABOUT_US,
}

export enum StoreInfoTypeMap {
  LOCATION,
  PHONE,
  EMAIL,
  ABOUT_US,
  BUSINESS_TIME,
}


export enum StudyServiceMap {
  COURSES,
  TIMETABLE,
  CHECK_IN,
  ID_CARD,
}

export enum CourseSortButton {
  DEFAULT,
  PRICE,
}

export enum CourseSortTypeMap {
  DEFAULT,
  PRICE_LOW_TO_HIGH,
  PRICE_HIGH_TO_LOW,
}
