export enum RouterMap {
  /**
   * 主页面
   */
  MAIN = 'Main',
  /**
   * 安全隐私也
   */
  SAFE = 'Safe',
  /**
   * 信息修改页
   */
  PROFILE_EDIT = 'ProfileEdit',
  /**
   * 快速登录页
   */
  QUICK_LOGIN = 'QuickLogin',
  /**
   * 相关设置页
   */
  SETTING = 'SettingPage',
  /**
   * 隐私协议页
   */
  PRIVACY_POLICY = 'PrivacyPolicy',
  /**
   * 语音播报页
   */
  VOICE_BROADCAST = 'VoiceBroadcast',
  /**
   * 生活指数页
   */
  INDICES = 'IndicesPage',
  /**
   * 开屏广告页
   */
  SPLASH_AD = 'SplashAd',
  /**
   * 字体设置页面
   */
  SETTING_FONT = 'SettingFont',
}