import { ServiceGridItem } from '../model/ServiceGridItem';

export const SERVICE_LIST: ServiceGridItem[] = [
  {
    label: $r('app.string.service_maincare'),
    icon: $r('app.media.service_maincare'),
  },
  {
    label: $r('app.string.service_food'),
    icon: $r('app.media.service_food'),
  },
  {
    label: $r('app.string.service_mumcare'),
    icon: $r('app.media.service_mumcare'),
  },
  {
    label: $r('app.string.service_env'),
    icon: $r('app.media.service_env'),
  },
  {
    label: $r('app.string.service_guide'),
    icon: $r('app.media.service_guide'),
  },
  {
    label: $r('app.string.service_kids'),
    icon: $r('app.media.service_kids'),
  },

];

export const BANNER_LIST: Resource[] = [
  $r('app.media.home_pic'),
  $r('app.media.store_pic1'),
  $r('app.media.store_pic2'),
  $r('app.media.store_pic1'),
];