
export enum AppStorageMap {
  HUAWEI_ACCOUNT = 'huaweiAccount',
  USER_INFO = 'userInfo',
}

export enum RouterMap {
  // 我的-修改个人信息
  MINE_PROFILE_EDIT = 'ProfileEditPage',
}

export enum DialogMap {
  BIND_PHONE_DIALOG = 'BindPhoneDialog',
}

export enum StoreBookingProjectMap {
  '超感式体验（90min）',
  '观光式体验（30min）',
}

export enum StoreBookingStatusMap {
  BOOKING_CANCEL = 0,
  BOOKING_SUCCESS = 1,
}