
export enum AppStorageMap {
  HUAWEI_ACCOUNT = 'huaweiAccount',
  USER_INFO = 'userInfo',
  ALL_COURSE_INFO = 'allCourseInfo',
}

export enum RouterMap {
  // 首页
  HOME = 'Home',
  // 课表中心
  COURSE_SCHEDULE = 'CourseSchedulePage',
  // 课程详情
  COURSE_DETAIL = 'CourseDetailPage',
  // 签到界面
  CLASS_SIGN_IN = 'ClassSignInPage',
}

export enum DialogMap {
  BIND_PHONE_DIALOG = 'BindPhoneDialog',
}

export enum ScheduleFlag {
  // 常规分布/自定义分布
  NORMAL = 'NORMAL',
  // 奇数周分布
  ODD_WEEK = 'ODD_WEEK',
  // 偶数周分布
  EVEN_WEEK = 'EVEN_WEEK',
}