/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class CheckInRecord {
  getFieldTypeMap() {
    let fieldTypeMap = new Map();
    fieldTypeMap.set('userId', 'String');
    fieldTypeMap.set('taskId', 'Integer');
    fieldTypeMap.set('activityId', 'Integer');
    fieldTypeMap.set('textDetail', 'Text');
    fieldTypeMap.set('pictureDetail', 'Text');
    fieldTypeMap.set('audioDetail', 'Text');
    fieldTypeMap.set('videoDetail', 'Text');
    fieldTypeMap.set('createTime', 'Date');
    fieldTypeMap.set('recordId', 'String');
    return fieldTypeMap;
  }

  getClassName() {
    return 'CheckInRecord';
  }

  getPrimaryKeyList() {
    let primaryKeyList = [];
    primaryKeyList.push('recordId');
    return primaryKeyList;
  }

  getIndexList() {
    let indexList = [];
    return indexList;
  }

  getEncryptedFieldList() {
    let encryptedFieldList = [];
    return encryptedFieldList;
  }

  setUserId(userId) {
    this.userId = userId;
  }

  getUserId() {
    return this.userId;
  }

  setTaskId(taskId) {
    this.taskId = taskId;
  }

  getTaskId() {
    return this.taskId;
  }

  setActivityId(activityId) {
    this.activityId = activityId;
  }

  getActivityId() {
    return this.activityId;
  }

  setTextDetail(textDetail) {
    this.textDetail = textDetail;
  }

  getTextDetail() {
    return this.textDetail;
  }

  setPictureDetail(pictureDetail) {
    this.pictureDetail = pictureDetail;
  }

  getPictureDetail() {
    return this.pictureDetail;
  }

  setAudioDetail(audioDetail) {
    this.audioDetail = audioDetail;
  }

  getAudioDetail() {
    return this.audioDetail;
  }

  setVideoDetail(videoDetail) {
    this.videoDetail = videoDetail;
  }

  getVideoDetail() {
    return this.videoDetail;
  }

  setCreateTime(createTime) {
    this.createTime = createTime;
  }

  getCreateTime() {
    return this.createTime;
  }

  setRecordId(recordId) {
    this.recordId = recordId;
  }

  getRecordId() {
    return this.recordId;
  }
}

module.exports = { CheckInRecord };
