/**
 * 通用常量
 */
export class Constants {
  static readonly SPACE_XXS: number = 4;
  static readonly SPACE_XS: number = 6;
  static readonly SPACE_S: number = 8;
  static readonly SPACE_M: number = 12;
  static readonly FULL_PERCENT: string = '100%';
  static readonly PADDING_S: number = 8;
  static readonly PADDING_M: number = 12;
  static readonly PADDING_L: number = 16;
  static readonly APP_ICON_W: number = 20;
  static readonly SOURCE: string = 'FormCard';
  static readonly NEWS_DETAIL_PAGE: string = 'NewsDetailPage';
}