/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class CourseInfo {
  getFieldTypeMap() {
    let fieldTypeMap = new Map();
    fieldTypeMap.set('courseId', 'Integer');
    fieldTypeMap.set('type', 'Integer');
    fieldTypeMap.set('name', 'String');
    fieldTypeMap.set('summary', 'String');
    fieldTypeMap.set('detail', 'Text');
    fieldTypeMap.set('mainDiagram', 'String');
    fieldTypeMap.set('price', 'Float');
    fieldTypeMap.set('expireType', 'Integer');
    fieldTypeMap.set('startTime', 'String');
    fieldTypeMap.set('endTime', 'String');
    fieldTypeMap.set('orderTime', 'String');
    fieldTypeMap.set('classHour', 'Integer');
    fieldTypeMap.set('status', 'Integer');
    fieldTypeMap.set('currentHour', 'Integer');
    fieldTypeMap.set('timetable', 'String');
    return fieldTypeMap;
  }

  getClassName() {
    return 'CourseInfo';
  }

  getPrimaryKeyList() {
    let primaryKeyList = [];
    primaryKeyList.push('courseId');
    return primaryKeyList;
  }

  getIndexList() {
    let indexList = [];
    return indexList;
  }

  getEncryptedFieldList() {
    let encryptedFieldList = [];
    return encryptedFieldList;
  }

  setCourseId(courseId) {
    this.courseId = courseId;
  }

  getCourseId() {
    return this.courseId;
  }

  setType(type) {
    this.type = type;
  }

  getType() {
    return this.type;
  }

  setName(name) {
    this.name = name;
  }

  getName() {
    return this.name;
  }

  setSummary(summary) {
    this.summary = summary;
  }

  getSummary() {
    return this.summary;
  }

  setDetail(detail) {
    this.detail = detail;
  }

  getDetail() {
    return this.detail;
  }

  setMainDiagram(mainDiagram) {
    this.mainDiagram = mainDiagram;
  }

  getMainDiagram() {
    return this.mainDiagram;
  }

  setPrice(price) {
    this.price = price;
  }

  getPrice() {
    return this.price;
  }

  setExpireType(expireType) {
    this.expireType = expireType;
  }

  getExpireType() {
    return this.expireType;
  }

  setStartTime(startTime) {
    this.startTime = startTime;
  }

  getStartTime() {
    return this.startTime;
  }

  setEndTime(endTime) {
    this.endTime = endTime;
  }

  getEndTime() {
    return this.endTime;
  }

  setOrderTime(orderTime) {
    this.orderTime = orderTime;
  }

  getOrderTime() {
    return this.orderTime;
  }

  setClassHour(classHour) {
    this.classHour = classHour;
  }

  getClassHour() {
    return this.classHour;
  }

  setStatus(status) {
    this.status = status;
  }

  getStatus() {
    return this.status;
  }

  setCurrentHour(currentHour) {
    this.currentHour = currentHour;
  }

  getCurrentHour() {
    return this.currentHour;
  }

  setTimetable(timetable) {
    this.timetable = timetable;
  }

  getTimetable() {
    return this.timetable;
  }
}

module.exports = { CourseInfo };
