export enum AppStorageMap {
  HUAWEI_ACCOUNT = 'huaweiAccount',
  USER_INFO = 'userInfo',
  SHOPPING_BASKET = 'shoppingBasket',
}

export enum RouterMap {
  //  首页
  Home = 'HomePage',
  //  菜品详情
  DISHES = 'DishesPage',
  //  搜索页面
  SEARCH = 'SearchPage',
  //  搜索结果
  RESULT = 'ResultPage',
  //  浏览记录
  BROWSING_HISTORY = 'BrowsingHistory',
  //  我的菜谱
  MY_RECIPE = 'MyRecipe',
  //  我的收藏
  MY_COLLECTION = 'MyCollection',
  //  设置
  SETTINGS_PAGE = 'SettingsPage',
  //  个人信息
  PERSON_INFO_PAGE = 'PersonalInfo',
  //  隐私协议
  PRIVACY_PAGE = 'PrivacyPage',
  //  清除缓存
  CACHE_PAGE = 'CachePage',
  //  隐私政策
  TERMS_OF_SERVICE_PAGE = 'TermsOfServicePage',
  //  用户协议
  PRIVACY_POLICY_PAGE = 'PrivacyPolicyPage',
  //  快速登录
  QUICK_LOGIN_PAGE = 'QuickLoginPage',
  // 菜篮子
  SHOPPING_BASKET_PAGE = 'ShoppingBasketPage',
  // 上传菜谱
  UPLOAD_RECIPE = 'UploadRecipe'
}