/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { UtilLog } from '@hw-agconnect/util-log';

/**
 * 日志打印类
 */
class Logger {
  private domain: number;
  private prefix: string;
  private format: string = '%{public}s, %{public}s';

  constructor(prefix: string) {
    this.prefix = prefix;
    this.domain = 0xFF00;
    this.format.toUpperCase();
  }

  debug(...args: string[]) {
    UtilLog.debug(this.domain, this.prefix, this.format, args);
  }

  info(...args: string[]) {
    UtilLog.info(this.domain, this.prefix, this.format, args);
  }

  warn(...args: string[]) {
    UtilLog.warn(this.domain, this.prefix, this.format, args);
  }

  error(...args: string[]) {
    UtilLog.error(this.domain, this.prefix, this.format, args);
  }
}

export default new Logger('Decompression');