export { MainPage } from './src/main/ets/pages/MainPage';

export { DemoPage } from './src/main/ets/pages/DemoPage';

export { MessagePage } from './src/main/ets/pages/MessagePage';
export { ValuationPageBuilder } from './src/main/ets/components/valuation/ValuationPage';
export { ProductCategoryPageBuilder } from './src/main/ets/components/valuation/ProductCategoryPage';
export { OrderSubmitPageBuilder} from './src/main/ets/components/valuation/OrderSubmitPage';
export { AddBankCardPageBuilder} from './src/main/ets/components/valuation/AddBankCardPage';
export { ValuationInfoHostPageBuilder } from './src/main/ets/components/valuation/ValuationInfoHostPage';
export { ModifyAppointmentInformationPageBuilder } from './src/main/ets/components/valuation/ModifyAppointmentInformationPage';
