// 天气卡片圆角半径
export const CARD_BORDER_RADIUS: number = 16;
// 手机端实时天气卡片高度
export const MOBILE_REALTIME_CARD_HEIGHT: number = 232;
// 大屏实时天气卡片头部边距
export const LARGE_HEADER_MARGIN: Margin = { top: 24, bottom: 24 };
// 逐小时列表项宽度
export const HOURLY_ITEM_WIDTH: number = 48;
// 逐天列表项宽度
export const DAILY_ITEM_WIDTH: number = 56;
// 生活指数项间距-小屏
export const INDICES_ITEM_SPACE_SM: number = 8;
// 生活指数项间距-大屏
export const INDICES_ITEM_SPACE_LG: number = 16;
// 生活指数列数-中屏
export const INDICES_COLUMNS_MD: number = 4;
// 生活指数列数-小屏
export const INDICES_COLUMNS_SM: number = 2;
// 卡片间分隔区域高度
export const DIVIDER_HEIGHT: number = 10;
// 语音播报图标尺寸
export const SPEAKER_ICON_SIZE: number = 19;
// 语音播报按钮尺寸
export const SPEAKER_BTN_SIZE: number = 24;
// 背景遮罩最大不透明度
export const MASK_MAX_OPACITY: number = 0.8;
