/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class home_service {
    name: string;
    pic: string;
    id: string;

    constructor() {
    }

    getFieldTypeMap():  Map<string, string> {
        let fieldTypeMap = new Map<string, string>();
        fieldTypeMap.set('name', 'String');
        fieldTypeMap.set('pic', 'String');
        fieldTypeMap.set('id', 'String');
        return fieldTypeMap;
    }

    getClassName(): string {
        return 'home_service';
    }

    getPrimaryKeyList(): string[] {
        let primaryKeyList: string[] = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList(): string[] {
        let indexList: string[] = [];
        indexList.push('name');
        return indexList;
    }

    getEncryptedFieldList(): string[] {
        let encryptedFieldList: string[] = [];
        return encryptedFieldList;
    }

    setName(name: string): void {
        this.name = name;
    }

    getName(): string  {
        return this.name;
    }

    setPic(pic: string): void {
        this.pic = pic;
    }

    getPic(): string  {
        return this.pic;
    }

    setId(id: string): void {
        this.id = id;
    }

    getId(): string  {
        return this.id;
    }

    static parseFrom(inputObject: any): home_service {
        let result = new home_service();
        if (!inputObject) {
            return result;
        }
        if (inputObject.name) {
            result.name = inputObject.name;
        }
        if (inputObject.pic) {
            result.pic = inputObject.pic;
        }
        if (inputObject.id) {
            result.id = inputObject.id;
        }
        return result;
    }
}

export { home_service };