let myHandler = async function (event, context, callback, logger) {
    logger.info(`Input event: ${JSON.stringify(event)}`);
    let televisionList = [
        {
            id: 'television_1',
            type: 4,
            title: '江苏卫视',
            description: '电影是以运动影像为核心，结合声音的艺术形式，通过光化学记录或数字化技术实现影像创作与传播。电影是以运动影像为核心，结合声音的艺术形式，通过光化学记录或数字化技术实现影像创作与传播。',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    updateTime: '2025/10/03',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_2',
            type: 4,
            title: '新闻卫视',
            description: '曲风空灵又带着忧伤，三个乐章情绪层层递进，是古典主义转向浪漫主义的代表性钢琴作品。',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    updateTime: '2025/10/03',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_3',
            type: 4,
            title: 'bubble卫视',
            description: '覆盖干货干货、悬念吸睛、情绪共鸣三大方向，适配文章、短视频、课程等不同场景，兼顾传播性与价值感：',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    updateTime: '2025/10/03',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_1.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_4',
            type: 4,
            title: '体育卫视',
            description: '新闻资讯、生活服务、情感互动、娱乐潮流等主流都市广播节目，兼顾接地气的烟火气、实用性与传播力，符合广播 “听觉传播 + 即时互动” 的特性',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    updateTime: '2025/10/03',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_2.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_5',
            type: 4,
            title: '财富卫视',
            description: '适配儿歌、动画、早教启蒙、生活习惯、亲子互动等宝宝巴士核心内容，突出 “低幼友好、韵律感强、启蒙性 + 趣味性”，符合 2-6 岁宝宝认知特点和家长对 “寓教于乐” 的需求',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    updateTime: '2025/10/03',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_3.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_6',
            type: 4,
            title: '经济卫视',
            description: '适配电台节目、播客、短视频、文章等场景，突出 “治愈、放松、疗愈、陪伴” 核心，用温柔的语言传递温暖与力量，贴合 “心灵温泉” 的疗愈属性',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    updateTime: '2025/10/03',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    updateTime: '2025/10/02',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_4.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_7',
            type: 4,
            title: '农业卫视',
            description: '适配黑胶收藏、音乐推荐、复古生活、店铺宣传、内容创作等场景，突出 “复古质感、音质情怀、收藏价值、仪式感” 核心，兼顾文艺感与传播力，贴合黑胶唱片的独特魅力',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    updateTime: '2025/10/03',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_5.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_8',
            type: 4,
            title: '水利卫视',
            description: '适配行情解读、板块分析、投资指南、热点追踪等场景，突出 “时效性、数据支撑、涨跌信号、赚钱机会”，兼顾专业度与吸睛力，贴合股民对行情动态、风险预警、掘金方向的核心需求',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    updateTime: '2025/10/03',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_6.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_9',
            type: 4,
            title: '时尚卫视',
            description: '适配穿搭分享、美妆教程、潮流解读、生活方式等内容场景，突出 “个性、专业、实用、吸睛”，兼顾时尚感与传播力，贴合达人 “引领审美、干货输出、人格化表达” 的核心需求',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    updateTime: '2025/10/03',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    duration: 425386,
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_7.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_10',
            type: 4,
            title: '动画卫视',
            description: '适配美食制作、探店分享、日常干饭、烘焙甜品等场景，突出 “温暖、治愈、烟火气、治愈情绪” 核心，用柔软的语言传递美食的慰藉感，贴合 “治愈系” 的温柔调性',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    updateTime: '2025/10/03',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_8.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
        {
            id: 'television_11',
            type: 4,
            title: '开心卫视',
            description: '适配短视频、直播、图文创作等场景，突出 “脑洞、反差、沙雕、互动感”，用幽默夸张的表达打破常规，贴合搞怪达人 “解压、搞笑、吸睛” 的核心需求，自带传播属性',
            isFollow: false,
            coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
            total: 9,
            section: [
                {
                    id: 'section_1',
                    title: '本月新上电影,有你想看的吗?',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    updateTime: '2025/10/03',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: false,
                },
                {
                    id: 'section_2',
                    title: '精彩不能停,最新精彩悬疑影片再来一波!',
                    updateTime: '2025/10/02',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: false,
                },
                {
                    id: 'section_3',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/10/01',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/a20e0965e56a4dc498fc33ee23750c0d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_4',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/28',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/daa381bc66604878bd403ef77c1c458d.mp4',
                    needVip: true,
                },
                {
                    id: 'section_5',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/27',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/95c55588cbdb4b999eeae0c069dbc5d9.mp4',
                    needVip: true,
                },
                {
                    id: 'section_6',
                    title: '本月新上电影,有你想看的吗?',
                    updateTime: '2025/9/26',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/73253951779340a39a7763e29f40ccb8.mp4',
                    needVip: true,
                },
                {
                    id: 'section_7',
                    title: '人气佳作电影推荐榜单',
                    updateTime: '2025/9/25',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_8',
                    title: '独家专访吕克贝松-他拒绝回答不喜欢的问题',
                    updateTime: '2025/9/24',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_9',
                    title: '当喜剧遇到其它元素会有多精彩?几部私房电影推荐 ',
                    updateTime: '2025/9/23',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
                {
                    id: 'section_10',
                    title: '10部最佳奥斯卡影片，经典永不过时',
                    updateTime: '2025/9/22',
                    duration: 425386,
                    coverUrl: 'https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/audio%2Fbroadcast_9.jpg',
                    sectionUrl: 'https://www-file.huawei.com/admin/asset/v1/pro/view/1fe450a626db4fc9ad86a960c60ea993.mp4',
                    needVip: true,
                },
            ],
        },
    ];
    logger.info(`televisionList: ${televisionList}`);
    let result = { televisionList }
    let res = new context.HTTPResponse(result, {
        "faas-content-type": "json"
    }, "application/json", "200");

    callback(res);
};

module.exports.myHandler = myHandler;