/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class OrderInfo {
  getFieldTypeMap() {
    let fieldTypeMap = new Map();
    fieldTypeMap.set('orderNo', 'String');
    fieldTypeMap.set('userId', 'String');
    fieldTypeMap.set('orderTime', 'Date');
    fieldTypeMap.set('orderStatus', 'Integer');
    fieldTypeMap.set('paymentMethod', 'Integer');
    fieldTypeMap.set('totalPrice', 'Float');
    fieldTypeMap.set('orderStr', 'String');
    fieldTypeMap.set('student', 'String');
    fieldTypeMap.set('phone', 'String');
    fieldTypeMap.set('courseInfo', 'Text');
    fieldTypeMap.set('expireTime', 'Date');
    return fieldTypeMap;
  }

  getClassName() {
    return 'OrderInfo';
  }

  getPrimaryKeyList() {
    let primaryKeyList = [];
    primaryKeyList.push('orderNo');
    return primaryKeyList;
  }

  getIndexList() {
    let indexList = [];
    return indexList;
  }

  getEncryptedFieldList() {
    let encryptedFieldList = [];
    return encryptedFieldList;
  }

  setOrderNo(orderNo) {
    this.orderNo = orderNo;
  }

  getOrderNo() {
    return this.orderNo;
  }

  setUserId(userId) {
    this.userId = userId;
  }

  getUserId() {
    return this.userId;
  }

  setOrderTime(orderTime) {
    this.orderTime = orderTime;
  }

  getOrderTime() {
    return this.orderTime;
  }

  setOrderStatus(orderStatus) {
    this.orderStatus = orderStatus;
  }

  getOrderStatus() {
    return this.orderStatus;
  }

  setPaymentMethod(paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  getPaymentMethod() {
    return this.paymentMethod;
  }

  setTotalPrice(totalPrice) {
    this.totalPrice = totalPrice;
  }

  getTotalPrice() {
    return this.totalPrice;
  }

  setOrderStr(orderStr) {
    this.orderStr = orderStr;
  }

  getOrderStr() {
    return this.orderStr;
  }

  setStudent(student) {
    this.student = student;
  }

  getStudent() {
    return this.student;
  }

  setPhone(phone) {
    this.phone = phone;
  }

  getPhone() {
    return this.phone;
  }

  setCourseInfo(courseInfo) {
    this.courseInfo = courseInfo;
  }

  getCourseInfo() {
    return this.courseInfo;
  }

  setExpireTime(expireTime) {
    this.expireTime = expireTime;
  }

  getExpireTime() {
    return this.expireTime;
  }
}

module.exports = { OrderInfo };
