/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class UserInfo {
  getFieldTypeMap() {
    let fieldTypeMap = new Map();
    fieldTypeMap.set('userId', 'String');
    fieldTypeMap.set('avatar', 'String');
    fieldTypeMap.set('nickname', 'String');
    fieldTypeMap.set('phone', 'String');
    fieldTypeMap.set('studentID', 'String');
    fieldTypeMap.set('wechat', 'String');
    fieldTypeMap.set('birthday', 'String');
    return fieldTypeMap;
  }

  getClassName() {
    return 'UserInfo';
  }

  getPrimaryKeyList() {
    let primaryKeyList = [];
    primaryKeyList.push('userId');
    return primaryKeyList;
  }

  getIndexList() {
    let indexList = [];
    return indexList;
  }

  getEncryptedFieldList() {
    let encryptedFieldList = [];
    return encryptedFieldList;
  }

  setUserId(userId) {
    this.userId = userId;
  }

  getUserId() {
    return this.userId;
  }

  setAvatar(avatar) {
    this.avatar = avatar;
  }

  getAvatar() {
    return this.avatar;
  }

  setNickname(nickname) {
    this.nickname = nickname;
  }

  getNickname() {
    return this.nickname;
  }

  setPhone(phone) {
    this.phone = phone;
  }

  getPhone() {
    return this.phone;
  }

  setStudentID(studentID) {
    this.studentID = studentID;
  }

  getStudentID() {
    return this.studentID;
  }

  setWechat(wechat) {
    this.wechat = wechat;
  }

  getWechat() {
    return this.wechat;
  }

  setBirthday(birthday) {
    this.birthday = birthday;
  }

  getBirthday() {
    return this.birthday;
  }
}

module.exports = { UserInfo };
